apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapproxy-deployment
spec:
  template:
    spec:
      containers:
        - name: mapproxy
          volumeMounts:
            - name: mapproxy-configmap
              mountPath: /app/config
            - name: mapproxy-lock-data
              mountPath: /mnt/lock
      volumes:
        - name: mapproxy-configmap
          configMap:
            name: mapproxy-configmap-uat
            defaultMode: 292
            optional: false
        - name: mapproxy-lock-data
          persistentVolumeClaim:
            claimName: mapproxy-lock-data-uat
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
